services:
   frontend:
    build: ./frontend
    ports:
      - 3000:5173
    depends_on:
      - backend
   backend:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      DB_NAME: todo_db
      DB_USER: todo
      DB_PASSWORD: todo
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

   db:
     image: postgres:17
     environment:
       POSTGRES_DB: todo_db
       POSTGRES_USER: todo
       POSTGRES_PASSWORD: todo
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U todo -d todo_db"]
       interval: 10s
       timeout: 10s
       retries: 10
     volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
